// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: proto/match/match.proto

package match

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type State int32

const (
	State_Ready    State = 0
	State_Progress State = 1
	State_Suspend  State = 2
	State_Stop     State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "Ready",
		1: "Progress",
		2: "Suspend",
		3: "Stop",
	}
	State_value = map[string]int32{
		"Ready":    0,
		"Progress": 1,
		"Suspend":  2,
		"Stop":     3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_match_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_match_match_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_match_proto_rawDescGZIP(), []int{0}
}

var File_proto_match_match_proto protoreflect.FileDescriptor

var file_proto_match_match_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x2a, 0x37, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x03, 0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x3b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_match_match_proto_rawDescOnce sync.Once
	file_proto_match_match_proto_rawDescData = file_proto_match_match_proto_rawDesc
)

func file_proto_match_match_proto_rawDescGZIP() []byte {
	file_proto_match_match_proto_rawDescOnce.Do(func() {
		file_proto_match_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_match_match_proto_rawDescData)
	})
	return file_proto_match_match_proto_rawDescData
}

var file_proto_match_match_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_match_match_proto_goTypes = []interface{}{
	(State)(0), // 0: match.State
}
var file_proto_match_match_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_match_match_proto_init() }
func file_proto_match_match_proto_init() {
	if File_proto_match_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_match_match_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_match_match_proto_goTypes,
		DependencyIndexes: file_proto_match_match_proto_depIdxs,
		EnumInfos:         file_proto_match_match_proto_enumTypes,
	}.Build()
	File_proto_match_match_proto = out.File
	file_proto_match_match_proto_rawDesc = nil
	file_proto_match_match_proto_goTypes = nil
	file_proto_match_match_proto_depIdxs = nil
}
