// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/match/match.proto

package match

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_Buy  Type = 0
	Type_Sell Type = 1
)

var Type_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}

var Type_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1ebb343b10e6eea4, []int{0}
}

func init() {
	proto.RegisterEnum("match.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("proto/match/match.proto", fileDescriptor_1ebb343b10e6eea4) }

var fileDescriptor_1ebb343b10e6eea4 = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x80, 0x90, 0x7a, 0x60, 0x11, 0x21, 0x56, 0x30, 0x47,
	0x4b, 0x92, 0x8b, 0x25, 0xa4, 0xb2, 0x20, 0x55, 0x88, 0x9d, 0x8b, 0xd9, 0xa9, 0xb4, 0x52, 0x80,
	0x41, 0x88, 0x83, 0x8b, 0x25, 0x38, 0x35, 0x27, 0x47, 0x80, 0x31, 0x89, 0x0d, 0xac, 0xd0, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x89, 0x57, 0x17, 0x1c, 0x43, 0x00, 0x00, 0x00,
}
