// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: proto/bid/bid.proto

package bid

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Type int32

const (
	Type_Buy  Type = 0
	Type_Sell Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Buy",
		1: "Sell",
	}
	Type_value = map[string]int32{
		"Buy":  0,
		"Sell": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bid_bid_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_bid_bid_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_bid_bid_proto_rawDescGZIP(), []int{0}
}

type Sort int32

const (
	Sort_Asc  Sort = 0
	Sort_Desc Sort = 1
)

// Enum value maps for Sort.
var (
	Sort_name = map[int32]string{
		0: "Asc",
		1: "Desc",
	}
	Sort_value = map[string]int32{
		"Asc":  0,
		"Desc": 1,
	}
)

func (x Sort) Enum() *Sort {
	p := new(Sort)
	*p = x
	return p
}

func (x Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bid_bid_proto_enumTypes[1].Descriptor()
}

func (Sort) Type() protoreflect.EnumType {
	return &file_proto_bid_bid_proto_enumTypes[1]
}

func (x Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort.Descriptor instead.
func (Sort) EnumDescriptor() ([]byte, []int) {
	return file_proto_bid_bid_proto_rawDescGZIP(), []int{1}
}

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid      int32   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Uuid     string  `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name     string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Amount   float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Price    float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	CreateAt int64   `protobuf:"varint,7,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Type     Type    `protobuf:"varint,8,opt,name=type,proto3,enum=bid.Type" json:"type,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bid_bid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bid_bid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_proto_bid_bid_proto_rawDescGZIP(), []int{0}
}

func (x *Unit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Unit) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Unit) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Unit) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Unit) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Unit) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Unit) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Buy
}

var File_proto_bid_bid_proto protoreflect.FileDescriptor

var file_proto_bid_bid_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x64, 0x2f, 0x62, 0x69, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x62, 0x69, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x04, 0x55,
	0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x19, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07,
	0x0a, 0x03, 0x42, 0x75, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65, 0x6c, 0x6c, 0x10,
	0x01, 0x2a, 0x19, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x73, 0x63,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07,
	0x62, 0x69, 0x64, 0x3b, 0x62, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bid_bid_proto_rawDescOnce sync.Once
	file_proto_bid_bid_proto_rawDescData = file_proto_bid_bid_proto_rawDesc
)

func file_proto_bid_bid_proto_rawDescGZIP() []byte {
	file_proto_bid_bid_proto_rawDescOnce.Do(func() {
		file_proto_bid_bid_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bid_bid_proto_rawDescData)
	})
	return file_proto_bid_bid_proto_rawDescData
}

var file_proto_bid_bid_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bid_bid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_bid_bid_proto_goTypes = []interface{}{
	(Type)(0),    // 0: bid.Type
	(Sort)(0),    // 1: bid.Sort
	(*Unit)(nil), // 2: bid.Unit
}
var file_proto_bid_bid_proto_depIdxs = []int32{
	0, // 0: bid.Unit.type:type_name -> bid.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bid_bid_proto_init() }
func file_proto_bid_bid_proto_init() {
	if File_proto_bid_bid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bid_bid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bid_bid_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bid_bid_proto_goTypes,
		DependencyIndexes: file_proto_bid_bid_proto_depIdxs,
		EnumInfos:         file_proto_bid_bid_proto_enumTypes,
		MessageInfos:      file_proto_bid_bid_proto_msgTypes,
	}.Build()
	File_proto_bid_bid_proto = out.File
	file_proto_bid_bid_proto_rawDesc = nil
	file_proto_bid_bid_proto_goTypes = nil
	file_proto_bid_bid_proto_depIdxs = nil
}
